### ISSUE TITLE
Voir pour déploiement par Gitub actions 

### ISSUE THREAD

**Issue by LeandreWeb** [LeandreWeb/F1#266]

**Comment by LeandreWeb** [comment]
Chat gpt m'a donner ses infos 
name: Deploy to Server

```
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H your-server-ip >> ~/.ssh/known_hosts

    - name: Deploy code
      run: |
        ssh user@your-server-ip "cd /path/to/remote/directory && git pull"

```
